
server:
  port: 8080
#  servlet:
#    context-path: /user

spring:
  profiles:
    active: local
  application:
    name: userapplication
  datasource:
    driver-class-name: org.h2.Driver
    #       url: jdbc:h2:mem:simpleuserdb
    url: jdbc:h2:file:~/databaseH2/userdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console